service: serverless-line-bot

provider:
  name: aws
  runtime: nodejs4.3
  region: ap-northeast-1
  environment:
    lineChannelAccessToken: ${env:LINE_CHANNEL_ACCESS_TOKEN}


functions:
  webhook:
    handler: webhook.main
    events:
      - http: POST webhook
